### ISSUE TITLE
Clarifying usage of clusterExpressionPatterns when multiple conditions exist

### ISSUE THREAD

**Issue by TJonCooper** [statOmics/tradeSeq#110]
```
data("sce", package = "bioc2020trajectories")
condRes <- conditionTest(sce, l2fc = log2(2))
condRes<-condRes[order(condRes$waldStat, decreasing = FALSE),]
nPointsClus <- 20
clusPat <- clusterExpressionPatterns(sce, nPoints = nPointsClus,genes = rownames(condRes)[1:100])
dd<-clusPat$yhatScaled
```

As far as I understand, clusterExpressionPatterns first employs predictSmooth for each gene listed and centres + scales the data to have a variance of 1 - is that correct?. When multiple conditions are present, dd contains 40 columns (presumably 1:20, 21:40 split by condition - which is which condition?) and it has scaled the entire vector. 

Is there any way to prevent it from splitting by condition (besides editing the sce pheno data)? i.e. have it cluster based on lineage alone, regardless of condition. 

Secondly, I'm 99% certain that it's okay - but I wanted to verify that it still makes mathematical sense to scale the entire vector (as opposed to each condition separately) and that this does not introduce any artefacts/issues? 

Thank you!

**Comment by HectorRDB** [comment]
Hi @TJonCooper 
1/ It's not entirely clear to me what you mean. When we cluster, each gene is assigned to one cluster based on its estimated mean expression. This mean expression is condition-dependent and lineage-dependent since we fit a smoother for every lineage and condition. However, the gene itself is assigned to only one cluster (i.e. that cluster assignment is not lineage or condition specific).  

2/ That's a very good point. We actually made that mistake in the first version of the workshop, scaling each condition separately. However, it makes more sense to scale each gene along all its coordinates (i.e. across all lineages and conditions). To understand, consider a gene where the condition lead to a constant increase in expression (across pseudotime). If you scale and center each condition separately, this will disappear. 

Hope that helps

**Comment by TJonCooper** [comment]
Many thanks for your reply - this brings clarity to my issues. One more question: from the above code, `dd<-clusPat$yhatScaled`, it's not immediately clear which columns pertain to which condition? The headings are "l1:t0" for example, so we can distinguish lineages, but I don't see anything specifying the condition. Is this something you can add?

**Comment by lsole92** [comment]
Hi!
I have been using this amazing package for my analysis. I have two conditions across the same trajectory and now I would like to plot a heatmap showing the DEG in the trajectories of my two conditions (like you did in the Trajectories workshop). However, I am having some problems that I think are related to the scaling by condition and not by lineage of predictSmooth, like you were discussing here. 

I have genes in which the level at the end of the pseudotime for both conditions is similar but the starting point is lower in one. Then when I try to do the heatmap it seems like it is actually way more expressed in that condition, but I think it is just because it is scaling separately so the difference between start and end in that condition is higher. (In the images attached as an example, condition yellow is the first part of the heatmap and purple the second. The first row is the same gene as in the plotSmoothers graph but both graphs don´t really match).

So I wanted to ask if you have found a way for scaling by lineage and not condition as TJonCooper suggested?

Thanks in advance!
[Lyz1_WTvsKO.pdf](https://github.com/statOmics/tradeSeq/files/5844256/Lyz1_WTvsKO.pdf)
[Rplot09.pdf](https://github.com/statOmics/tradeSeq/files/5844260/Rplot09.pdf)

**Comment by HectorRDB** [comment]
Hi @TJonCooper 
To reply to your final question:
The latest devel version of tradeSeq now uses the notation l1_2 (for lineage 1, condition 2 for example) so it should be clearer now. Thanks for pointing this out

**Comment by HectorRDB** [comment]
@lsole92 
Thanks for using tradeSeq, we're glad you like it.
I am unsure about the plots you showed. The first one looks like the output of `plotSmoothers` but there seems to be no condition there. The second is a heatmap but it's not clear what 4 blocks (two by two) represent. Is that the lineages and the conditions? Moreover, it does not look like any scaling was done in the heatmap (i.e. values are still on the same scale, from 0 to 7). 
To answer your question however, you should scale the gene by grouping all lineages and conditions together. This way, the ordering of values between conditions is preserved. If you scale for each condition separatly (or for each lineage separatly), you will indeed produce artifacts. 
Hope that helps

**Comment by lsole92** [comment]
Hi @HectorRDB 
Sorry for coming back to you so late and sorry that my graphs were confusing...
I actually have a model with 5 lineages and 2 conditions (= 10 lineages) so I tried to simplify it but made it more confusing. I found what the problem was for my heatmaps, though. The name of the columns when calculating predictSmooth() was not correct and, thus, I was plotting the wrong columns in the heatmap. PredictSmooth would name the columns (with its respective points) in the following order: Lineage1_Cond1, Lineage2_Cond1,..., Lineage1_Cond2, Lineage2_Cond2,...   However, in reality the calculations would actually correspond to Lineage1_Cond1, Lineage1_Cond2, Lineage2_Cond1, Lineage_Cond2... I don´t know if the problem was mine or something from the function. 

I have another question about plotSmoothers. Is there a possibility to tell the function which lineages to plot?  In my case it makes it very confusing to have 10 lineages in one graph and I would like to only plot one lineage in the two conditions (=2 lines instead of 10). The only way I found was to create a new tradeseq object with only one lineage and naming each condition as if it was an independent lineage (that´s what I did in the first graph I uploaded and that´s why it didn´t seem like they were two conditions but two independent lineages). 

Thank you very much in advance!

**Comment by HectorRDB** [comment]
Hi @lsole92 
No problem. We have made recent updates to tradeSeq that could impact your two questions.
1/ Can you update the package and check if the naming is correct
2/ You can now specify colors for points and curves in plotSmoothers. So if you pass it "transparent" for the lineages you are not interested in, it should not display them.

**Comment by ammarsabircheema** [comment]
Hi,

Can you please tell me how can I increase the number of clusters using this code? This code is taken from tradeseq tutorial, I tried to increase the number of clusters myself but it did not work, so Is there a way I can increase the number of clusters that are printed at the end?

```
nPointsClus <- 45
clusPat <- clusterExpressionPatterns(sce, nPoints = nPointsClus,
                                     genes = rownames(expression_matrix_scapin@assays$RNA@data)[1:300])
clusterLabels <- primaryCluster(clusPat$rsec)

cUniq <- unique(clusterLabels)
cUniq <- cUniq[!cUniq == -1] # remove unclustered genes


plot_list = list()
for (xx in cUniq[1:18]) {
  cId <- which(clusterLabels == xx)
  p <- ggplot(data = data.frame(x = 1:nPointsClus,
                                y = rep(range(clusPat$yhatScaled[cId, ]),
                                        nPointsClus / 2)),
              aes(x = x, y = y)) +
    geom_point(alpha = 0) +
    labs(title = paste0("Cluster ", xx),  x = "Pseudotime", y = "Normalized expression") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5))
  for (ii in 1:length(cId)) {
    geneId <- rownames(clusPat$yhatScaled)[cId[ii]]
    p <- p +
      geom_line(data = data.frame(x = rep(1:nPointsClus, 2),
                                  y = clusPat$yhatScaled[geneId, ],
                                  lineage = rep(0:3, each = nPointsClus)),
                aes(col = as.character(lineage), group = lineage), lwd = 1.5)
  }
  p <- p + guides(color = FALSE) +
    scale_color_manual(values = c("orange", "darkseagreen3","red","blue"),
                       breaks = c("0", "1"))  
  plot_list[[i]] = p
   

}
```

**Comment by carbycrab** [comment]
Hi @HectorRDB 

Thank you so much for developing the tradeseq conditions analysis. It's such an awesome addition to package! I have a similar question. I have 4 lineages and 2 conditions (8 lineages total) but am only interested in visualizing four of them on plotSmoothers. When I tried passing "transparent" to lineages I want to exclude in the `curvesCol` argument, my lineages of interest look partially cut off (I think they are hidden behind the transparent ones). Additionally, I'm wondering what I should pass to the `pointCol` argument to highlight only the cells on my desired lineages.

I am also interested in creating a pseudotime heatmap, with the gene rows clustered together (k= 5) based on expression pattern  as opposed to clustered by dendrogram. However, I am getting this warning `Warning message:
In cor(t(M)) : the standard deviation is zero` at this step `row_dist <- as.dist((1 - cor(t(M)))/2)`  when I run the code below resulting in downstream error `Error in hclust(row_dist, method = "ward.D2") : 
  NA/NaN/Inf in foreign function call (arg 10)` :

```
# Clustered pseudotime Heatmap
yhatSmooth <- predictSmooth(fitgam, gene = genes, nPoints = 1000, tidy = FALSE)
yhatSmoothScaled <- t(scale(t(yhatSmooth)))
M <- yhatSmoothScaled[,1001:2000]
M <- as.matrix(M)
M[M < -3] <- -3
M[M > 3] <- 3
row_dist <- as.dist((1 - cor(t(M)))/2)
hcl <- hclust(row_dist, method="ward.D2")
k_val <- 5
gene_cluster <- factor(cutree(hcl, k=k_val))
annotation_row <- data.frame(Cluster=gene_cluster)

heatSmooth_cond1 <- pheatmap(M,useRaster=T, cluster_cols=F, 
                             cluster_rows=T,show_rownames=F, show_colnames=F, 
                             clustering_distance_rows=row_dist,
                             clustering_method="ward.D2", cutree_rows=k_val, 
                             annotation_row=annotation_row, border_color=NA)

heatSmooth_cond2 <- pheatmap(yhatSmoothScaled[heatSmooth_cond1$tree_row$order, 5001:6000],
                                 cluster_cols = FALSE, cluster_rows = F,
                                 show_rownames = FALSE, show_colnames = FALSE, main = "VS",
                                 legend = FALSE, silent = TRUE
)
```
There aren't any NA values in the matrix and I tried removing all rows with zeros in them but the error still remains. This code works when `M<-yhatSmooth[1001:2000]` and I add a scaling step but unfortunately this doesn't scale the data with all lineages/conditions present. 

Thanks again for the help!

**Comment by HectorRDB** [comment]
Hi @carbycrab 
Thanks for using `tradeSeq`, we're glad you like it.

+ You also need to specify `border=FALSE`, otherwise, the curves still have a white border (hence the cut)
+ The `pointCols` argument takes as input a vector of length the number of cells. Assign one color per cell based on condition, including transparent for those that should be hidden.
+ I am unsure what you are trying to achieve. The dendogramm will cluster the genes based on expression pattern as well, but only on the first condition. If you want to cluster them together, I would use scale after filtering, not before (and remove the thresholding at +/- 3). 

Hope that helps
Hector

**Comment by nouhaylaeraysy** [comment]
hello @HectorRDB  i have a question please about plotsmoothers,i print the plot for several gene in loop my question is how i can print just a plotsmoothers for gene that have a dynamic expression not continuous?
thank you in advance.
Best.
