### ISSUE TITLE
Set range of plotted values

### ISSUE THREAD

**Issue by balthasar0810** [statOmics/tradeSeq#125]
Hi,

plotting 
plotGeneCount(slingshotDataset, counts, gene = gene)

provides a heatmap plot. How can I adjust the value range of "logged count of gene" shown in the plot? Say, I want to color-code values from 1 to 2?

Best, CHris

**Comment by koenvandenberge** [comment]
Hi @balthasar0810 

Thanks for raising the question. As I understand it, you'd like to color code the cells based on a limited range of the gene expression of the gene you're looking at, rather than the entire range of gene expression values.
This is a pretty specific question and it won't be at the top of our to do list for a while. If you want, you can try it out yourself by adapting the [function](https://github.com/statOmics/tradeSeq/blob/master/R/plotGeneCount.R). If it works, feel free to contribute to the package through a pull request.

**Comment by HectorRDB** [comment]
Hi @balthasar0810 
To pile up on what @koenvandenberge said, the `plotGeneCount` function returns a ggplot object so you can change the color scheme as you would do with any ggplot object, using the `scale_color_...`

**Comment by balthasar0810** [comment]
Thanks for the replies! Sorry, I just saw that, too, that a ggplot object is returned...
