### ISSUE TITLE
Question about mapping columns in heatmap to cell type

### ISSUE THREAD

**Issue by s2hui** [statOmics/tradeSeq#131]
Hello,

I was following your [tutorial](https://kstreet13.github.io/bioc2020trajectories/articles/worksh) to create a heatmap and was wondering how to map the columns of the heatmap to cell type?  

I wanted to create a heatmap like the one in the paper:
![image](https://user-images.githubusercontent.com/10944134/109668633-5a1df180-7b3f-11eb-9693-23e99cb7a442.png)
where the columns are annotated according to the cell type along the trajectory.

I tried to take a stab at running the code in the code [here](https://github.com/statOmics/tradeSeqPaper/blob/master/case/fletcher/20180830_caseStudyFletcher_v5_tradeR.Rmd#L363) but ran into several problems.  

My data has two lineages.  This is part of the code I am running:

```
gamList <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights, genes = var_genes,verbose=T, parallel=TRUE, BPPARAM = BPPARAM, sce=FALSE)
assocRes <- associationTest(gamList, global = TRUE, lineages = TRUE)
deAssoc1 <- rownames(assocRes)[p.adjust(assocRes$pvalue_1, "fdr") <= 0.05]
o1 <- order(assocRes[deAssoc1, "waldStat_1"], decreasing = TRUE)
top200Assoc <- deAssoc1[o1[1:200]] 
```

when I run:

`df <- .getPredictRangeDf(gamList[[1]], lineageId = 1, nPoints = 100)
`

I get an error:

Error in dm[1, ] : incorrect number of dimensions.

In addition:

* pst variable is set to a few things but doesn't seem to be used (line [368](https://github.com/statOmics/tradeSeqPaper/blob/master/case/fletcher/20180830_caseStudyFletcher_v5_tradeR.Rmd#L368) )
* line [373](https://github.com/statOmics/tradeSeqPaper/blob/master/case/fletcher/20180830_caseStudyFletcher_v5_tradeR.Rmd#L373) contains a bunch of hardcoded lines and I wasn't sure how these index value ranges were obtained

Perhaps there is a more straightforward way of mapping cell types to the columns of the heatmap that I have overlooked.

Thanks for your help.

**Comment by HectorRDB** [comment]
Hi @s2hui 
The code has clearly evolved a lot since the paper... 
There is now a convenient `predictSmooth` function that should return the necessary input to pheatmap, similarly to what we did in the recent [bioconductor workshop](https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html#visualization-of-de-genes). 
If you have two lineages, I would recommend doing two heatmaps. However, note that the scaling should be common. [This part of the workshop](https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html#heatmaps-of-genes-de-between-conditions) does it. Although it is for two conditions, the code should be quite straightforward to tune for two lineages. 
However, `predictSmooth` will not return values at exact cells, instead it returns the mean smoother at equally spaced pseudotime values. 
If you want to add celltype information on top, you have a few options: 
+ similarly to what was done in the tradeSeq paper, you can manually decide on pseudotime cutoffs for celltype and pseudotime matching and rename the columns accordingly. 
+ You can use the `predictCells` function. In that setting, each cell will have a cell type directly. However, the heatmap won't be as smooth. 
There is no easy way to do it. Indeed, clustering implies a discrete partition of the data while pseudotime assumes a continuum so there is no general rule for how to properly match one to the other.

**Comment by s2hui** [comment]
Hi, Thanks very much for your insight.  It makes sense and I will look into the options you mentioned.
