### ISSUE TITLE
Strange and specific error with fitgam and multiple conditions

### ISSUE THREAD

**Issue by DustinSokolowski** [statOmics/tradeSeq#139]
Hey!

Thank you for your great tool! 

I have been using slingshot and tradeseq together and it has already unveiled aspects of my data that I would have never otherwise seen.

I think you have a small but in the fitGam function when you have these specific conditions
1) When the input data is a SingleCellExperiment object
2) When Conditions were stated in the fitGam function
3) When the slingshot function has extension="n"

I've tried nearly every permutation of this and the error only shows up if these conditions are met. The error itself (I think) happens after fitGam is run and when tradeseq is being put into colData.
`sce <- fitGAM(sce, conditions = factor(colData(sce)$Condition),
           nknots = k_choose, genes = names(rVar5k))`

![image](https://user-images.githubusercontent.com/56414662/114788146-f6e2ca00-9d4e-11eb-8855-d247878109a8.png)

The kicker (for me) is that when I have the exact same input object but parse it first, then it works fine.
`sce1 <- fitGAM(logcounts(sce), sds = SlingshotDataSet(sce),conditions = factor(colData(sce)$Condition),
              nknots = k_choose, genes = names(rVar5k))`

I imagine it's a pretty small bug but it may be worth fixing or seeing if it's something bigger. If you'd like my data specifically I can send it. fitGam with it takes 1 hour.

Best,
Dustin

**Comment by koenvandenberge** [comment]
Hi @DustinSokolowski,

Thanks, we appreciate it you using `tradeSeq`!

I think that this could be a bug that we have previously fixed in https://github.com/statOmics/tradeSeq/commit/810bc5f709181f1c4a405932330e25031f247bb5.  So if you're using `tradeSeq` version `1.5.07` or lower, I'd recommend to update the package by re-installing it from our GitHub repo. Let us know if this doesn't fix it!

Best,
Koen

**Comment by DustinSokolowski** [comment]
Hey!

I updated and it worked great. Sorry about that!
Dustin
