### ISSUE TITLE
a question about balance score

### ISSUE THREAD

**Issue by liuweihanty** [statOmics/tradeSeq#140]
Hi there developers of tradeSeq,
I have a question regarding the balance score mentioned in the multi condition analysis vignette.https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html

I have three samples, a control, and two gene X knock down samples. I integrated them by Seurat SCT protocol and below is my balance score graph.
If I understood it correctly, the lower the score, the more confident we are to infer a global trajectory based on integrated object, rather than infer separate trajectories for each treatment conditions correct? Based on the vignette there doesn't seem to be a clear cut threshold of when to make this judgement. Therefore I'm really interested to ask what your thought on my balance score, do you think this is ok to infer a global trajectory?(there are several major high score regions so I'm not sure..) Thank you very much for any inputs!
![Picture 1](https://user-images.githubusercontent.com/43444815/115632801-1f7a3f00-a2ce-11eb-9c48-b25600da9819.png)

**Comment by HectorRDB** [comment]
Hi @liuweihanty 
We have now published a [full paper](https://www.biorxiv.org/content/10.1101/2021.03.09.433671v1) on this topic with an associated R package named [condiments](https://hectorrdb.github.io/condiments/) to develop a more systematic approach to this question. 
If you want, you can open an issue on the condiments workflow [here](https://github.com/HectorRDB/condiments/issues) so that other users can also benefit from the answer.
Best

**Comment by liuweihanty** [comment]
Thanks! @HectorRDB I will read the paper and package first :)
