### ISSUE TITLE
How to select top genes for fitGAM?

### ISSUE THREAD

**Issue by YuliaInn** [statOmics/tradeSeq#150]
Hello,

I am following [this tutorial](https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html). I tried to run fitGAM for ~25K genes ~6K cells and 2 conditions but the predicted runtime was 3 days. I saw your recommendations to use highly variable genes in similar issues. Does gene=seq_len(2000) uses 2000 highly variable genes or random 2000 genes? If not, how do you usually remove non-variable genes? Cause Seurat doesn't let me remove them.

Also, I saw that you all were discussing the runtime issues of fitGAM a year ago. Do you have any updates or solutions for that now? For 2000 gene, my estimated runtime is 6 hours.

Thank you

**Comment by HectorRDB** [comment]
Hi @YuliaInn 
Indeed the runtimes issue is still there. We have a lot of ideas to speed it up but as of now, nothing has been implemented. 

If you input `genes=seq_len(2000)`, it will just run fitGAM on the first 2000 genes of the object (probably by alphabetical order, depending on the structure). 
You can pass indexes or genes names. If you've run the seurat tool to find variable genes and obtained a list `hvg_genes` for examples, you can do `genes = rownames(object)[rownames(object) %in% hvg_genes]` for exemple.

Hopes that helps

**Comment by kstreet13** [comment]
Sorry for not adding this earlier but for posterity, I would also recommend checking out deviance-based filtering. Since variance is generally correlated with mean expression level, selecting for highly variable genes can end up being roughly the same as selecting highly expressed genes, which aren't _always_ the most informative. [This vignette](http://bioconductor.org/packages/release/bioc/vignettes/scry/inst/doc/scry.html) demonstrates how to perform feature selection with deviance using the `scry` package.
