### ISSUE TITLE
Memory limitation for large dataset

### ISSUE THREAD

**Issue by ppaxisa** [statOmics/tradeSeq#159]
Hi, I am trying to use `tradeSeq` on a large dataset: ~250K cells by ~10K genes. I am also adding a model matrix `U` with ~70 indicator variables to account for various batch effects. Running `evaluateK` with a dgcMatrix `GEX` and `pseudotime` with one lineage (one column):

`icMat <- evaluateK(GEX,
                    pseudotime = pseudotime,
                    U = U,
                    parallel = F)`

I get the following error:

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'counts' in selecting a method for function 'evaluateK': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102`

What would be the best approach here? I could downsample the number of cells or use less genes? If I understand correctly the default here is 500 genes to test K so the problem is more about the number of cells?

Thanks

**Comment by koenvandenberge** [comment]
Hi @ppaxisa,

Thank you for sharing this.

Note that [internally we're converting the sparse matrix to a dense matrix](https://github.com/statOmics/tradeSeq/blob/master/R/evaluateK.R#L211) as we've previously had issues with allowing a full sparse matrix support. It could be that it's this step that's already giving us memory issues.

Your dataset is very large indeed and we haven't yet tried running `tradeSeq` on datasets with 250k cells. I'm not quite sure therefore where the error is coming from, i.e., from converting to a dense matrix, `mgcv` or somewhere else. 
Here are a few suggestions that could get us going:

 - Could you please share the output after running `traceback()` after getting the error?
 - Could you try running `icMat <- evaluateK(as.matrix(GEX[1:10,]), pseudotime = pseudotime, U = U, parallel = F)`, and similar (if previous works) `icMat <- evaluateK(as.matrix(GEX[1:500,]), pseudotime = pseudotime, U = U, parallel = F)`, to check if it's the conversion to a dense matrix (which seems likely).
 - If that's not it, could you set `nGenes=2` to make sure it's only a problem of the number of cells?
 - If this still errors, could you set `offset = rep(log(1), ncol(GEX))` in `evaluateK` to make sure it's not because of the normalization?

**Comment by ppaxisa** [comment]
Hi @koenvandenberge,

Thanks for the reply, I noticed afterwards the conversion to dense matrix, that's probably the issue. 

When running `evaluateK` on small number of genes (2,10,100) I get the following error:

```
> res100 <- evaluateK(GEX[1:100,],
                    pseudotime = pseudotime,
                    cellWeights = matrix(1, nrow = nrow(pseudotime)), # only one lineage
                    U = U,
                    parallel = F)
**Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'**
> 
> 
> 
> traceback()
9: sample.int(length(x), size, replace, prob)
8: sample(seq_len(nrow(counts)), nGenes)
7: .evaluateK(counts = counts, k = k, U = U, pseudotime = pseudotime, 
       cellWeights = cellWeights, plot = plot, nGenes = nGenes, 
       weights = weights, offset = offset, verbose = verbose, conditions = conditions, 
       parallel = parallel, BPPARAM = BPPARAM, control = control, 
       family = family, gcv = gcv, ...)
6: .local(counts, ...)
5: evaluateK(counts = as.matrix(counts), k = k, nGenes = nGenes, 
       sds = sds, pseudotime = pseudotime, cellWeights = cellWeights, 
       plot = plot, U = U, weights = weights, offset = offset, aicDiff = aicDiff, 
       verbose = verbose, conditions = conditions, parallel = parallel, 
       BPPARAM = BPPARAM, control = control, family = family, gcv = gcv, 
       ...)
4: evaluateK(counts = as.matrix(counts), k = k, nGenes = nGenes, 
       sds = sds, pseudotime = pseudotime, cellWeights = cellWeights, 
       plot = plot, U = U, weights = weights, offset = offset, aicDiff = aicDiff, 
       verbose = verbose, conditions = conditions, parallel = parallel, 
       BPPARAM = BPPARAM, control = control, family = family, gcv = gcv, 
       ...)
3: .local(counts, ...)
2: evaluateK(GEX[1:100, ], pseudotime = pseudotime, cellWeights = matrix(1, 
       nrow = nrow(pseudotime)), U = U, parallel = F)
1: evaluateK(GEX[1:100, ], pseudotime = pseudotime, cellWeights = matrix(1, 
       nrow = nrow(pseudotime)), U = U, parallel = F)
```


Which I think is related to the library normalization from `edgeR:: calcnormfactors`? I'm guessing there is not enough data in each cell to properly calculate normalization factors.

When running with 500 genes as below, it works fine.

```
res500 <- evaluateK(GEX[1:500,],
                    pseudotime = pseudotime,
                    cellWeights = matrix(1, nrow = nrow(pseudotime)), # only one lineage
                    U = U,
                    parallel = F)
```

When running with `nGenes = 2`:

```
> res <- evaluateK(GEX,
                    pseudotime = pseudotime,
                    cellWeights = matrix(1, nrow = nrow(pseudotime)), # only one lineage
                    U = U,
                    parallel = F,
                    nGenes = 2)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'counts' in selecting a method for function 'evaluateK': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
> traceback()
10: h(simpleError(msg, call))
9: .handleSimpleError(function (cond) 
   .Internal(C_tryCatchHelper(addr, 1L, cond)), "Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102", 
       base::quote(asMethod(object)))
8: asMethod(object)
7: as(x, "matrix")
6: as.matrix.Matrix(counts)
5: as.matrix(counts)
4: evaluateK(counts = as.matrix(counts), k = k, nGenes = nGenes, 
       sds = sds, pseudotime = pseudotime, cellWeights = cellWeights, 
       plot = plot, U = U, weights = weights, offset = offset, aicDiff = aicDiff, 
       verbose = verbose, conditions = conditions, parallel = parallel, 
       BPPARAM = BPPARAM, control = control, family = family, gcv = gcv, 
       ...)
3: .local(counts, ...)
2: evaluateK(GEX, pseudotime = pseudotime, cellWeights = matrix(1, 
       nrow = nrow(pseudotime)), U = U, parallel = F, nGenes = 2)
1: evaluateK(GEX, pseudotime = pseudotime, cellWeights = matrix(1, 
       nrow = nrow(pseudotime)), U = U, parallel = F, nGenes = 2)
> 


```

I get again the memory error.


When running with `offset = rep(log(1), ncol(GEX))` I get the same error and traceback.


I understand that the full matrix is only needed for `edgeR:: calcnormfactors`, as all subsequent modeling step are done on each genes individually? 

I was wondering if I can calculate the normalization factors beforehand with another method, and then partition my sparse matrix into small chunks of few hundred genes before running `evaluateK` and `fitGAM` on it, specifying the normalization factors with the `offset` argument? Would that make sense?

thanks again for the help!

**Comment by koenvandenberge** [comment]
Hi @ppaxisa 

The first code chunk errored because `nGenes` is by default equal to `500` and we only give 100 genes to `evaluateK`. I forgot to change the `nGenes` default on the code I suggested, my bad. This then also explains why the second chunk works, instead.

The memory error indeed comes from trying to convert the sparse matrix into a dense matrix. `edgeR::calcNormFactors` can actually handle sparse matrices.

I have updated `evaluateK` and it should now allow for large sparse matrices as input without converting the full matrix to a dense matrix. However, within `fitGAM` it will convert the matrix of the randomly selected genes (hence 500 genes by default) to a dense matrix. But this shouldn't be an issue on your system since your second chunk ran. The only difference between the current modifications and your second code chunk is that now you'll normalize using all the genes, and not just the subset.

Let me know if this works for you.

**Comment by ppaxisa** [comment]
Hi @koenvandenberge,

Thanks I think that works for me. I would just point out that I am not sure that `edgeR::calcNormFactors` will actually handle the sparse matrix, it looks like it will convert internally to a dense matrix from looking at the [source code](https://rdrr.io/bioc/edgeR/src/R/calcNormFactors.R). Is that right? Obviously nothing you could do if that's the case.

**Comment by koenvandenberge** [comment]
Hi @ppaxisa 

I had just checked whether `edgeR::calcNormFactors` accepts a sparse matrix, in order to identify the root of the error.
It is true, as you say, that it does convert the sparse matrix to a dense matrix. But then I do find it surprising that you're running into memory issues when `evaluateK` converts the matrix to a dense matrix, but not when `calcNormFactors` does this...

If you're planning to fit all genes and you're still having the problem when running `fitGAM`, it would actually be useful to follow what you previously wrote: (a) normalize using all genes, (b) run `fitGAM` on chunks of your matrix, providing the normalization factors on the entire data matrix.

**Comment by ppaxisa** [comment]
Hi @koenvandenberge,

Thanks for looking into this and thanks again for the package. I think that closes the issue.
