### ISSUE TITLE
PlotGeneCount color levels change internally

### ISSUE THREAD

**Issue by DustinSokolowski** [statOmics/tradeSeq#161]
Hey!

Thank you for the fantastic package and tool. It has aided hugely in multiple projects. As we are moving towards publishing, we're cleaning up the visualizations as much as possible. This includes having the cluster colors on `PlotGeneCount` matching the cluster colors in Seurat's `DimPlot`. I am fairly certain that you internally re-order the clusters by their factor instead of by their index. I have provided a toy example below:

cluster_num <- c(0,1,10,2,20,6)

Reorder by number

sort(cluster_num) # 0 1 2 6 10 20

Reorder by character-factor

sort(as.factor(as.character(sce$ident))) # Levels: 0 1 10 2 20 6

Running the function normally, the order of idents and thus colors get re-ordered.

plotGeneCount(curve = crv, counts = counts,
              clusters = sce$ident,
              models = sce) + scale_color_manual(values=cluster_color$Color)

![image](https://user-images.githubusercontent.com/56414662/127552196-58521554-b883-4de1-8c9b-6f11898fef73.png)

I can force the cluster number into the index I'd like, but this will change the legend.

![image](https://user-images.githubusercontent.com/56414662/127552314-c23fd148-a1d9-4578-b7dd-45dc8ea42542.png)

Of course the bug is fairly minor and I totally understand if you don't have the time to fix it, but I thought you'd like to know.

Best!
Dustin

**Comment by koenvandenberge** [comment]
Hi @DustinSokolowski 

Thank you for the feedback, this is greatly appreciated.
If I understand correctly you're using the same colors using Seurat's `DimPlot` as well as using tradeSeq's `plotGeneCount`, and the issue you are having is that in Seurat the colors are assigned according to sorted numeric cluster numbers, but in tradeSeq they are assigned according to sorted factor-variable cluster numbers. Since the sorting isn't the same, different clusters are having different colors in Seurat's `DimPlot` as in tradeSeq's `plotGeneCount`. 
So in order to get what you want you'd have to be able to either (a) manually assign cluster colors to each cluster in `plotGeneCount`, or (b) have the option that in `plotGeneCount` orders the clusters numerically instead of using the factor variable. 

Is that correct or am I misreading your feedback?

**Comment by DustinSokolowski** [comment]
Hey! 

Yes that's exactly the feedback! Having the option (b) specifically would allow for the plotGeneCount colors match those in Seurat while keeping the legend consistent. 

Thanks so much!
Dustin

**Comment by koenvandenberge** [comment]
Hi @DustinSokolowski 

Note that most of our plotting functions, including `plotGeneCount` return a `ggplot` object and therefore you can tweak it post-creation.
In your case, you should easily be able to change both the colors as well as the legend labels. 
I provide a reproducible example below, let me know if this solves your issue.

```
set.seed(97)
library(slingshot)
data(crv, package="tradeSeq")
data(countMatrix, package="tradeSeq")
rd <- slingReducedDim(crv)
cl <- kmeans(rd, centers = 7)$cluster
lin <- getLineages(rd, clusterLabels = cl, start.clus = 4)
crv <- getCurves(lin)
counts <- as.matrix(countMatrix)
gamList <- fitGAM(counts = counts,
 pseudotime = slingPseudotime(crv, na = FALSE),
 cellWeights = slingCurveWeights(crv))
plotGeneCount(crv, counts, gene = "Mpo")


plotGeneCount(crv, counts, clusters=cl)


plotGeneCount(crv, counts, clusters=cl) + 
  scale_color_discrete(labels=letters[1:7]) + # change labels
  scale_color_manual(values=RColorBrewer::brewer.pal(7, "Dark2")) # change colors
```

**Comment by DustinSokolowski** [comment]
Hey!

More or less! that code still sorts the clusters by their character (e.g., 1, 10, 14, 2, 3) but by re-ordering the values within scale_color_manual I could circumvent the issue. Thank you so much for all of your help with this.

Best!
Dustin
