### ISSUE TITLE
high counts of unknown source

### ISSUE THREAD

**Issue by pchiang5** [statOmics/tradeSeq#176]
Hello,

I generated the pseudotime and weight data with the code below
`sce <- slingshot(sce, clusterLabels = 'GMM', reducedDim = 'PCA', start.clus = '4', end.clus = c( '0','5', '2', '1')))`

The trajectory looked reasonable (left panel of the attached figure).

When I proceeded to get the expression curve of a gene (code below), there were high counts at the beginning of the pseudotime (middle panel) that were not there in the corresponding UMAP plot with raw counts (right panel). 
Is there any reason for the discordance?   Thank you.

```
sce <- fitGAM(sce,  parallel = TRUE,  verbose = TRUE,  nknots = 7, BPPARAM = BiocParallel::bpparam())
plotSmoothers(sce, assays(sce)$counts, gene = GOI) 
```
![tradeseq](https://user-images.githubusercontent.com/29170925/144014292-c127e58b-b504-4552-b2b3-c79683b4c593.png)

**Comment by koenvandenberge** [comment]
Hi @pchiang5 

These are probably the cells in the yellow cluster.  Note that these cells are actually quite close to both lineage 2 as well as the starting point of your trajectory. Therefore, some of these will get assigned to the starting point.
If you believe that this should not be, you may consider trying to get lineage 2 from your starting cluster immediately to the yellow cluster, instead of first passing through the blue cluster in the middle.

Hope this helps.
Koen


![image](https://user-images.githubusercontent.com/10134844/144023759-81a3c201-f549-4b38-918e-230104586dc6.png)

**Comment by pchiang5** [comment]
Thank you @koenvandenberge!

I will consult the slingshot team about the issue.
