### ISSUE TITLE
fitGAM with different gene sets got different results of fitting curves for the same genes

### ISSUE THREAD

**Issue by Sophia409** [statOmics/tradeSeq#183]
Hi, all

Thanks for the wonderful package and tutorial!

I am reaching out for an issue with fitGAM(). When I was running fitGAM using 2000 variable features getting by Seurat:: FindIntegrationAnchors function, I had the following plot:
![图片](https://user-images.githubusercontent.com/30619010/149300176-38312b55-d63e-4683-85c0-25c3aa4975dd.png)
Then I used 767 marker genes from Seurat:: FindAllMarkers () as input, and fit the curve for the same gene, which got the following plot:
![图片](https://user-images.githubusercontent.com/30619010/149300215-8b9a342d-e537-4ace-9ea3-d05f98034e24.png)
As we can see, gene OXT ascends and then falls on lineage 2 at the first picture, but keeps very low expression at the second one. Also, gene TRH ascends and then falls on lineage 1, but keeps very low expression at the second one. What’s the reason? In this situation, which one should I choose? Do I need to choose one based on biological knowledge? Or is there any other method to evaluate it at the aspect of algorithm?

I read this related [issue ](https://github.com/statOmics/tradeSeq/issues/130)but still couldn’t find a clear solution. Could you help me figure it out here? Would be greatly appreciated!

Best regards and many thanks!
Sophia

**Comment by koenvandenberge** [comment]
Hi @Sophia409,

There are two reasons that can explain this. 

First, for cells that cannot unambiguously be assigned to a specific lineage, `fitGAM` will hard-assign them to a specific lineage prior to fitting. There is some randomness involved in this process, as we use the Multinomial distribution based on the weights provided by Slingshot (or other trajectory inference method) to assign cells to lineages. Therefore, running `fitGAM` several times will result in different assignments of cells to lineages. You can, however, fix this assignment by setting a seed prior to running `fitGAM`.

Second, since you have used different genes as input to `fitGAM`, the size factors used as normalization offsets will be different. If you provide the full count matrix as input but specify the genes you'd like to fit using the `genes` argument in `fitGAM`, that will calculate the normalization offset on the full data but only fit the genes you're interested in.

**Comment by Sophia409** [comment]
Hi, @koenvandenberge 

Thank you very much. 

Regarding the second reason you referred, I have to explain that I used different count matrixs (same cell with different genes) as input to fitGAM, not providing different genes as input. But the problems still exist, for example, the size factors used as normalization offsets will be different. Is that so?

**Comment by koenvandenberge** [comment]
Hi @Sophia409,

Yes, that is right, if you input different count matrices by subselecting different genes, the size factors will be (slightly) different.
