### ISSUE TITLE
fitGAM error: Error in vapply(slingCurves(x), function(pc)

### ISSUE THREAD

**Issue by grimwoo** [statOmics/tradeSeq#189]
Thanks for development of such a nice package. Here, I encountered error in function `fitGAM `. 

the original object contains 44123 cells, which may be the reason of memory issue.
`> sce`
`class: SingleCellExperiment 
dim: 68837 44123 
metadata(0):
assays(2): counts logcounts
rownames(68837): SAMD11 NOC2L ... Gm29554 FOXD1
rowData names(0):
colnames(44123): hsa.w6.10x_AAACCCATCGTGTGAT-1 hsa.w6.10x_AAACGAACAGTAACGG-1 ...
  P45X_TTTATGCCATAAGACA P45X_TTTCCTCCAGTCAGAG
colData names(30): orig.ident nCount_RNA ... slingCurveWeights_2 subset
reducedDimNames(2): PCA UMAP
mainExpName: RNA
altExpNames(0):`

`> sce <- fitGAM(counts = sce, conditions = sce$celltype.locat,nknots = 6)`
`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'counts' in selecting a method for function 'fitGAM': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102`

hence I subset the object, and unfortunately encountered another issue :
`> sce.subset`
`class: SingleCellExperiment 
dim: 68837 7333 
metadata(0):
assays(2): counts logcounts
rownames(68837): SAMD11 NOC2L ... Gm29554 FOXD1
rowData names(0):
colnames(7333): hsa.w6.10x_AAACCCATCGTGTGAT-1 hsa.w6.10x_AAAGGGCCAAATGCTC-1 ...
  P45X_TATCTCAGTCGATTGT P45X_TGTGTTTTCGACAGCC
colData names(30): orig.ident nCount_RNA ... slingCurveWeights_2 subset
reducedDimNames(2): PCA UMAP
mainExpName: RNA
altExpNames(0):`

`sce.subset <- fitGAM(counts = sce.subset, conditions = sce.subset$celltype.locat,nknots = 6)`
`Error in vapply(slingCurves(x), function(pc) { : 
  values must be length 7333,
 but FUN(X[[1]]) result is length 44123`

the error information of `44123` reminds me of the original object. I doublet if the error was triggered by the `subset` function.

could anyone help me with this issue? My `tradeSeq` version is 1.7.07.

**Comment by grimwoo** [comment]
I found the same result between `slingCurves(sce.subset)` and `slingCurves(sce)`. The subset function may failed in subset of the slingshot output inside `sce` object . Does anyone knows the correct way ?

**Comment by koenvandenberge** [comment]
This is a question that may be better directed to @kstreet13 on the Slingshot GitHub repository.

**Comment by kstreet13** [comment]
Yes, I think this is a Slingshot issue and it's related to the `SlingshotDataSet` class. I managed to reproduce it like this:
```
data("slingshotExample")
rd <- slingshotExample$rd
cl <- slingshotExample$cl
pto <- slingshot(rd, cl, start.clus = '1')
pto <- pto[-1, ]
slingPseudotime(pto) # no error
slingPseudotime(as.SlingshotDataSet(pto)) # error
```

The (now default) PseudotimeOrdering object doesn't rely on the curves in order to get pseudotime values, but the SlingshotDataSet does. This was actually a conscious design choice on my part. The curves are generally used for plotting and understanding how the psuedotimes were calculated, so I thought it would be important not to change them when subsetting the object (because subsetting doesn't change how the pseudotimes were originally calculated).

What version of Slingshot are you using, @grimwoo? It looks like it might be an older version, so there's a chance the updating to the latest release will solve this.

**Comment by grimwoo** [comment]
Thanks! @koenvandenberge
