### ISSUE TITLE
Error running patternTest

### ISSUE THREAD

**Issue by gabprg** [statOmics/tradeSeq#20]
Hello!

Thanks for putting together this package, it provides a great complement to slingshot! I was testing it out on one of my datasets, and I'm running into an error when running patternTest:

> patternRes <- patternTest(sce)
Error in t(L) %*% beta : non-conformable arguments
> traceback()
7: getEigenStatGAM(beta, Sigma, L)
6: FUN(X[[i]], ...)
5: lapply(seq_len(nrow(models)), function(ii) {
       beta <- t(rowData(models)$tradeSeq$beta[[1]][ii, ])
       Sigma <- rowData(models)$tradeSeq$Sigma[[ii]]
       getEigenStatGAM(beta, Sigma, L)
   })
4: .earlyDETest(models = models, global = global, pairwise = pairwise, 
       knots = NULL, nPoints = nPoints)
3: .local(models, ...)
2: patternTest(sce)
1: patternTest(sce)

I'm able to run all of the other differential test functions without any issues (and before this point I followed the code in the vignette exactly). Any chance you know what could be causing this?

Thanks!

Gabi

**Comment by koenvandenberge** [comment]
Thanks for reporting this.
This definitely should not happen. Which `tradeSeq` version are you using? Can you produce a reproducible example, or share (a subset of) the data and code with which you're experiencing this error?

**Comment by gabprg** [comment]
So interestingly, I was playing around with it some more, and if I reduced the number of knots from 7 to 4 it now works just fine. The model was having convergence issues with 7 knots, so perhaps that was what was throwing it off?

**Comment by koenvandenberge** [comment]
Well, the `Error in t(L) %*% beta : non-conformable arguments` error seems to suggest a bigger problem in the code. 
It seems like there must be something else going on as well, so even if you'd decide to proceed with a lower number of knots it would be useful for us to see if we can reproduce this and look into what's happening.

**Comment by gabprg** [comment]
Sounds good! I’ll try and go back to reproduce this and send you the details!

**Comment by NuhaSaud** [comment]
Hi,

I am trying to reproduce pattern test results in the simulated bifurcating datasets published in the paper, running 20190326_evaluateAllDyntoyBifurcating_R3.6.R script to get pattern test scores then performanceTIPlotBifurcation_acrossSimulations.R script to get the TPR-FDR plots. However, looking to the attached pval_dataset_number.txt files the majority of p-values are big values while the TPR-FDR plots look perfect.

Regards,
Nuha.      
[individualPerformance6To10.pdf](https://github.com/statOmics/tradeSeq/files/3917391/individualPerformance6To10.pdf)
[individualPerformanceFirst1To5.pdf](https://github.com/statOmics/tradeSeq/files/3917392/individualPerformanceFirst1To5.pdf)
[pvalDataset1.txt](https://github.com/statOmics/tradeSeq/files/3917393/pvalDataset1.txt)
[pvalDataset2.txt](https://github.com/statOmics/tradeSeq/files/3917394/pvalDataset2.txt)
[pvalDataset4.txt](https://github.com/statOmics/tradeSeq/files/3917395/pvalDataset4.txt)
[pvalDataset3.txt](https://github.com/statOmics/tradeSeq/files/3917396/pvalDataset3.txt)
[pvalDataset5.txt](https://github.com/statOmics/tradeSeq/files/3917397/pvalDataset5.txt)
[pvalDataset6.txt](https://github.com/statOmics/tradeSeq/files/3917398/pvalDataset6.txt)
[pvalDataset7.txt](https://github.com/statOmics/tradeSeq/files/3917399/pvalDataset7.txt)
[pvalDataset8.txt](https://github.com/statOmics/tradeSeq/files/3917400/pvalDataset8.txt)
[pvalDataset9.txt](https://github.com/statOmics/tradeSeq/files/3917401/pvalDataset9.txt)
[pvalDataset10.txt](https://github.com/statOmics/tradeSeq/files/3917402/pvalDataset10.txt)
[bifurcating_all 10 dataset.pdf](https://github.com/statOmics/tradeSeq/files/3917404/bifurcating_all.10.dataset.pdf)

**Comment by koenvandenberge** [comment]
Hi, 

Please direct such issues to the tradeSeqPaper repository and create a new issue.
The majority of p-values may be not small, but that is also what one might expect if 80% of the genes are not DE. Our paper mentions that we have 20% DE genes for 5000 genes in each simulated bifurcating dataset. I imported your `pvalDataset1.txt` file and I find 1054 p-values < 0.01, likely containing many of the 1000 truly DE genes.

We realize that the FDR-TPR curves look too good to be true, since the simulated datasets are too easy and too clean to be fully representative for realistic real scRNA-seq datasets and we acknowledge that in our manuscript. However, we have found them useful for ranking the different methods that are available.

Koen

**Comment by NuhaSaud** [comment]
Hi Koen,

Thank you for the fast response and sorry to post in the wrong Github repository. However, the FDR-TPR curves I obtained from the simulation code are different from the ones published in the paper and in the supplementary files. 

Nuha.

**Comment by koenvandenberge** [comment]
Hi Nuha,

How different are they? It may be because of small changes in tradeSeq. 
Are the plots you attach in your message above the plots that you are referring to?

Those FDR-TPR plots are indeed a bit different from the preprint, because we have evaluated an optimal number of knots to run tradeSeq. While the preprint uses 10 knots, the updated scripts use only 4 knots. This is decided based on our new `evaluateK` function.
