### ISSUE TITLE
Finds and orders `reduced` gene expressoin along a lineage

### ISSUE THREAD

**Issue by pchiang5** [statOmics/tradeSeq#243]
Hello,

I have obtained a beautiful order of peaks with cascade.R. Thank you.

Is there a way to find the reduced gene expression and order them as well? It is like a reverse format of the original cascade and orders them by the timings of the reduction. This function would be useful to find key gene loss during differentiation.

**Comment by koenvandenberge** [comment]
Hi @pchiang5,

I guess that makes you the first user of this functionality! We have just posted a preprint that explains how we do this, which you can read [here](https://www.biorxiv.org/content/10.1101/2023.10.26.564041v1) if interested.

What do you mean with "reduced gene expression" and "the reduction"? I think I am not completely understanding the question, here.

**Comment by pchiang5** [comment]
Hi @koenvandenberge 

Thank you for the tool and the reference!

The reduction means if there are some genes active in the original cluster (high at time == 0) and their levels wane or reduce along a trajectory (lower or become 0 at the trajectory end), is it possible to align these genes according to the times of disappearance by modifying the code below?

```
 ## calculate p-values using testing against a threshold and select relevant genes.
            # We do not consider negative first derivatives here since we're focused on peaks.
            testStats <- lapply(derAllGenes, function(x){
              der <- x[,1]
              derSD <- x[,2]
              testStat <- (abs(der)-derivativeThreshold) / derSD
              pvals <- pmin(1,(1-pnorm(testStat)))
              pvals[der < derivativeThreshold] <- 1
              return(list(testStat=testStat,
                          pvals=pvals))
            })
            pvalAll <- lapply(testStats, function(x) x$pvals)
            testAll <- lapply(testStats, function(x) x$testStat)
            names(pvalAll) <- names(testAll) <- genes
            # Check significance.
            peakGenes <- genes[unlist(lapply(pvalAll, function(x) any(x <= derPvalThreshold)))]
            pvalAll <- pvalAll[peakGenes]
            message(paste0((length(peakGenes) / length(genes)) * 100,"% of genes are increasing in expression."))
```

**Comment by koenvandenberge** [comment]
Hi @pchiang5 

Interesting question. 
I have not thought about this very thoroughly, but a couple of thoughts come to mind.

- Here, we are using the derivatives to check for genes with significantly increasing expression. You could indeed use that code to discover genes with significantly decreasing expression as a function of time, which seems to be what you're looking for. You would only have to test for significant negative first derivatives, instead of testing for significant positive first derivatives.
- After selecting that set of genes, it depends on how you define "waning/reducing" gene expression levels. You could for example, select genes that are decreasing and consistently stay low by considering the set of genes from step 1, and checking whether they do not have a significant positive first derivative after they had their significant negative first derivative. This could be interpreted as "the gene significantly decreased in expression, and after that it did not significantly increase in expression".
- This does not mean that the gene is expressed at a low level; it may decrease to a moderate level of expression and stay there. So to limit yourself to genes that are virtually non-expressed, would require you to look at the estimated mean expressions of the smoother (using e.g. `predictSmooth`).

Hope this helps.

**Comment by pchiang5** [comment]
Thank you @koenvandenberge!
I will try and see how it works.
