### ISSUE TITLE
Interpretive power of reported p-values

### ISSUE THREAD

**Issue by TobiTekath** [statOmics/tradeSeq#36]
Hi,
I tested your new package with great interest. Some questions arose regarding the p-values of the available statistical tests.

Just for context: As you know, the probably most-used analysis for RNA-seq data is DE calling. There are various methods to obtain interpretive p-values, which are seen by most people as statistical valid. Is there a huge difference to the tradeSeq p-values for a "DE calling along a latent time"?

1.  I read in your publication, that you view the reported "[...] p-values simply as useful numerical summaries for ranking the genes". Would you argue, that a probabilistic interpretation of these p-values would be incorrect (or at least not favourable)? Are there any new assumptions for the tests that do not simply arise from the nature of scRNA-seq data? 

1. Is the assumption correct, that all reported p-values are not multiple testing corrected?

Thanks in advance.

Best,
Tobi

**Comment by HectorRDB** [comment]
Hi @TobiTekath 
Thanks for your interest in tradeSeq. 
Those are very interesting questions. Let me try to give you a few answers. 

Indeed, RNA-Seq is mostly used for DE calling. In that setting, the usual workflow is normalization, finding clusters and DE assessment. Therefore, because those steps all use the same data, the probabilistic interpretation of p-values is not valid. I would refer you to [this paper by Zang et al](https://www.sciencedirect.com/science/article/abs/pii/S2405471219302698?via%3Dihub) that discuss the issue of running clustering + DE on the same data. 

1/ Therefore, since in tradeSeq, we have a workflow of normalization + trajectory inference + DE, the same caveats are present, which explain our reasoning. We discuss this somewhat in [the discussion section of our paper](https://www.nature.com/articles/s41467-020-14766-3#Sec9) (2nd and 4th paragraphs). 

2/ In tradeSeq, multiple testing can happen from two directions. a) Running the same test on many genes and b) running many tests on the same gene. Those two things can of course be complemented. Therefore, multiple testing correction should be done by the user after running all their tests.

Let me know if you have further questions,

Best

**Comment by HectorRDB** [comment]
Closing since no new response
