### ISSUE TITLE
Change colour for plotSmoothers

### ISSUE THREAD

**Issue by e1992** [statOmics/tradeSeq#39]
Hi, how can I change the colours when using plotSmoothers() ?
When I try and use geom_point() etc etc, I just plot new points over existing ones. 
Thanks!

**Comment by HectorRDB** [comment]
Hi,
If you want to change the colors for new ones, you can add the  `scale_color_manual(..)` to the ggplot object. Note that it will also change the colors of the curve.

If you want to color the points by something else, then you have two quick options.
1/ Indeed add new points with geom_point. You can choose the size of the points and the alpha in plotSmoothers so set both to zero.
2/ You can modify the code from plotSmoothers (in essence create your own function). Just run `plotSmoothers` (no space) to see the code.

We are working on updating the plotting function so that they can take as input a singlecellexperiment object and have options to color by columns in the metadata but this may take some time.
Let me know if that work
Best

**Comment by e1992** [comment]
Worked perfectly with `scale_color_manual(values =c(..))`
Thanks! Thanks for all your work with Trade-seq, its made my analysis so much better. 

That would be great to be able to colour by metadata!

**Comment by HectorRDB** [comment]
I'm glad it work and that you like tradeSeq. I will close the issue but I'll tag you here whenever we get around to do this.

**Comment by skannan4** [comment]
Sorry to resuscitate a dead issue! But since it's related I figured here might be a good spot. I'm using plotSmoothers with the SCE option, and trying to manually change colours. But scale_colour_manual only changes the colours for the points, not the smoothed lines (this is true whether I set a condition column or not). I'm not a ggplot2 expert, but I think it might be because in the plotSmoothers code the colours for the lines are set as a parameter to geom_line() rather than as an aesthetic? This means that scale_colour_manual will affect the aesthetics mapping (which holds for the points) but not the hardcoded lines. Any way around this? (I can just define my own plotSmoothers for now but figured this might be of relevance to others).

**Comment by koenvandenberge** [comment]
Hi @skannan4 

Note that in the latest version, `plotSmoothers` has an argument `pointCol` which allows you to define colors for each cell, please see `?plotSmoothers`. But you make a good point that we should look into having a similar argument for the smoothers themselves. We will be working on it and will update you as soon as it is implemented.

**Comment by liuyigh** [comment]
For reference, another option is to export current plot as PDF, then customized the lines with Inkscape, you can choose from all kinds of colors and stroke styles as you desire.

**Comment by HectorRDB** [comment]
Well better late than never... 
There is now a new option called `curvesCol` in the `plotSmoothers` function that allows users to specify colors for each curve independently. 
You can use this with the latest version of `tradeSeq` from github. 
Best

**Comment by koenvandenberge** [comment]
Awesome, thanks Hector!!
