### ISSUE TITLE
Question about the Wald statistics 

### ISSUE THREAD

**Issue by bieniu777** [statOmics/tradeSeq#66]
Hello,

I was wondering if someone could explain the Wald statistics to me. I have two lineages that I am comparing. When I run startVsEndTest I can either choose lineages = TRUE or lineages = FALSE. When I choose lineages = TRUE, I get additional p values for each lineage. Is lineages = TRUE a more accurate way to look for gene changes in a particular lineage than when using lineages = FALSE? When I run the upregulated genes from one of my lineages (p value < 0.05 and logFC > 0) in the ToppFun analysis (looking for upregulated biological processes and pathways), I get different results for when I use lineages = TRUE (no results) and lineages = FALSE (biological processes and pathways identified). I am wondering which is more accurate to use here. Should I be using lineages = TRUE when I want to look at strictly one lineage and lineages = FALSE, when I run other tests comparing the two lineages? For instance for the earlyDETest?

Thanks,

Kamila

**Comment by koenvandenberge** [comment]
Hi,

Tests like the `startVsEndTest` are comparisons within a single lineage. The null hypothesis is that the average gene expression is identical at the start and at the end of a lineage, for a particular gene. If `lineages=FALSE`, you will get one column of Wald test statistics, and corresponding p-values. These are the results of a **global test**, i.e., performed across all lineages. Thus, you can think of these Wald test statistics, and corresponding p-values as summarizing evidence for the null hypothesis: is the average gene expression identical at the start versus the end of a lineage, **across all the lineages of my trajectory**? This test gathers evidence across all your lineages, and this is why we call it a global test.

If you set `lineages=TRUE`, then you will also get the global test results. But, you will also get Wald test statistics and p-values for each lineage separately. For example, if you run the example code from `?startVsEndTest`, you'd get

```
> library(tradeSeq)
> data(gamList, package = "tradeSeq")
> head(startVsEndTest(gamList, global = TRUE, lineages = TRUE))
                  waldStat df    pvalue waldStat_lineage1 df_lineage1 pvalue_lineage1 waldStat_lineage2
1700012B09Rik 1.489419e-16  2 1.0000000      1.453929e-16           1       1.0000000      3.548941e-18
1700017B05Rik 4.316466e-01  2 0.8058777      4.093973e-01           1       0.5222756      2.224933e-02
1700020L24Rik 1.489419e-16  2 1.0000000      1.453929e-16           1       1.0000000      3.548941e-18
1810009A15Rik 1.384770e+00  2 0.5003812      1.448834e-02           1       0.9041920      1.370282e+00
1810011H11Rik 1.489419e-16  2 1.0000000      1.453929e-16           1       1.0000000      3.548941e-18
1810027O10Rik 2.589421e+00  2 0.2739772      5.277397e-01           1       0.4675587      2.061681e+00
              df_lineage2 pvalue_lineage2 logFClineage1 logFClineage2
1700012B09Rik           1       1.0000000     0.9861345    -0.1417701
1700017B05Rik           1       0.8814257    -0.9678810     0.4140010
1700020L24Rik           1       1.0000000     0.9861345    -0.1417701
1810009A15Rik           1       0.2417635    -0.1818238     2.4017616
1810011H11Rik           1       1.0000000     0.9861345    -0.1417701
1810027O10Rik           1       0.1510435     1.0967420     2.0879539
```

The first three columns are about the global test. The next three columns are about the first lineage, and the following three about the second lineage. The final columns give you the log fold-change.

> Should I be using lineages = TRUE when I want to look at strictly one lineage and lineages = FALSE, when I run other tests comparing the two lineages? For instance for the earlyDETest?
If you'd want to focus on one lineages then, yes, you should use `lineages=TRUE` for tests like the `startVsEndTest` which are about one lineage. Note that the `earlyDETest` compares expression *between* lineages. Since you only have two lineages, there is only a single comparison to be made, which is comparing these two lineages to each other.

**Comment by bieniu777** [comment]
Thank you very much
