### ISSUE TITLE
Impossible to place a knot at all endpoints.Increase the number of knots to avoid this issue

### ISSUE THREAD

**Issue by simjbaum** [statOmics/tradeSeq#70]
Hi all,
I get this warning:
**“Impossible to place a knot at all endpoints.Increase the number of knots to avoid this issue.”**
Which is probably due to the different trajectories curves on my data which are not covered by underlying data (Pseudotime) when taking those trajectories separately. 
As it is a warning I would continue with the analysis, but would have the question if I need to take considerations on downstream steps due to this warning? For example when comparing the trajectories?

Thank you and best wishes,
Simon

```
# define a function for SLINGSHOT
cell_pal <- function(cell_vars, pal_fun,...) {
  if (is.numeric(cell_vars)) {
    pal <- pal_fun(100, ...)
    return(pal[cut(cell_vars, breaks = 100)])
  } else {
    categories <- sort(unique(cell_vars))
    pal <- setNames(pal_fun(length(categories), ...), categories)
    return(pal[cell_vars])
  }
}


####
# SLINGSHOT
####
sds <- slingshot(Embeddings(adata, "scvi_umap"), clusterLabels = adata$`luv0.1`, 
                 start.clus = 0, stretch = 0) 

cell_colors <- cell_pal(as.character(adata$`luv0.1`), brewer_pal("qual", "Set2"))
cell_colors_clust <- cell_pal(adata$`luv0.1`, hue_pal())
plot(reducedDim(sds), col = cell_colors_clust, pch = 16, cex = 0.5)
lines(sds, lwd = 2, type = 'lineages', col = 'black')

```

![image](https://user-images.githubusercontent.com/7283790/90786149-372d9d80-e2d1-11ea-91e1-835c6dc8d175.png)

```

nc <- 2
pt <- slingPseudotime(sds)
nms <- colnames(pt)
nr <- ceiling(length(nms)/nc)
pal <- viridis(100, end = 0.95)
par(mfrow = c(nr, nc))
for (i in nms) {
  colors <- pal[cut(pt[,i], breaks = 100)]
  plot(reducedDim(sds), col = colors, pch = 16, cex = 0.5, main = i)
  lines(sds, lwd = 2, col = 'black', type = 'lineages')
}


```
![image](https://user-images.githubusercontent.com/7283790/90786201-4a406d80-e2d1-11ea-81b4-f204a83af0f5.png)

```

adata <- SCTransform(adata, vars.to.regress = c("nCount_RNA","mito_fraction"), verbose = TRUE) 


### tradeSeq
# find K for negative binomial model
counts <- as.matrix(adata@assays$SCT@counts)

set.seed(10)
icMat <- evaluateK(counts = counts, sds = sds, k = 3:10, nGenes = 100,
                   verbose = TRUE, plot = TRUE)
print(icMat[1:2, ])


```

Warning message in .fitGAM(counts = countSub, U = U, pseudotime = pseudotime, cellWeights = cellWeights, :
“Impossible to place a knot at all endpoints.Increase the number of knots to avoid this issue.”

**Comment by koenvandenberge** [comment]
Hi Simon,

Thank you for sharing your code and figures together with this issue.

This warning is something that has caused a lot of confusion before, and we have removed the message from the most recent versions of `tradeSeq`. It is occurring because you have a number of (in your case, three) lineages with pretty comparable lengths. Getting knots at each endpoint would therefore result in an unreasonably high number of knots, so in that case we just get equally-spaced knots along pseudotime. 
Since the 'density' of your data is pretty comparable along the trajectory, it should not affect your downstream analysis too much, so you don't have to worry about it.

A couple of points:

 - are you confident in the clustering results you are getting based on the biology of the system you are looking at? It seems to me that you may have quite a large number of clusters, and you could check to get a reasonable cluster resolution using, for example, marker genes. The reason why I am pointing it out is that the trajectory inference heavily relies on the clustering result. For example, do you truly expect the two lineages ending in the final pink clusters to constitute different lineages?
 - it looks like you are using `sctransform` normalized counts as input to `tradeSeq`, if I read your code correctly? We do not recommend that, as `tradeSeq` uses the raw counts as input, since it is a count-based statistical model.

**Comment by simjbaum** [comment]
Hi,
Those are very good, points. I was removing the sctransform from the code and evaluating the robustness and marker genes of those clusters. This helped a lot,
best wishes,
Simon
