### ISSUE TITLE
clusterExpressionPatterns

### ISSUE THREAD

**Issue by tinggithub33** [statOmics/tradeSeq#77]
Hello,
Thank you for developing this great tradeSeq package!
I have a problem to get clusterExpressionPatterns run.
here are my codes:
1.fitGAM, I fit pseudotime with real timepoint, a total of 5 time points. therefore 4 knots were given. it is no problem to run this step.
sce <- fitGAM(counts = count1,
            pseudotime = timePT,
             cellWeights = weightM,
              verbose = TRUE, 
            nknots = 4)
2. run clusterExpressionPatterns
nPointsClus <- 20
clusPat <- clusterExpressionPatterns(sce, nPoints = nPointsClus,
                                     genes = rownames(counts)[1:200])

I got error message as:
         Note: Not all of the methods requested in 'reduceMethod' have been 
         calculated. Will calculate all the methods requested (any pre-existing 
         values -- filtering statistics or dimensionality reductions -- with these 
         names will be recalculated and overwritten): PCA.
         Error in .local(object, ...) :  the number of reducedDims dimensions must 
         be a value strictly greater than 0
         In addition: Warning message:
         In .local(object, ...) :
         User requested more dimensionality reduction dimensions than the 
         minimimum of number of rows and columns. Will return all dimensions.

what could be wrong? any comments will be greatly appreciated.

**Comment by koenvandenberge** [comment]
Hi @tinggithub33 

The error seems to suggest that you request more PCA dimensions than there are data points (which is `nPointsClus = 20` in your case), while that doesn't seem to be true. Just as a check, are you getting the same error if you set `nReducedDims = 5`?

If that doesn't work I'd be happy to take a look at what's wrong if you share your `sce` object. Alternatively, you could also consider clustering the genes using something like

```
ysmooth <- predictSmooth(models = sce, gene = rownames(counts)[1:200], nPoints = 20)
ysmoothScaled <- t(scale(t(ysmooth)))
rsec <- clusterExperiment::RSEC(t(yhatPatScaled))
```

which should be similar to using `clusterExpressionPatterns`.

**Comment by tinggithub33** [comment]
Hello@koenvandenberge,
Thank you for your response!
a quick question, how do you decide nPointsClus? does it depend on number of timepoint or knots?
any comments will be greatly appreciated.

**Comment by koenvandenberge** [comment]
The number of points you use for clustering is arbitrary, but ideally it should be a function of the complexity of the expression patterns that you are observing. For example, you do not need a lot of points to describe a linear expression function over pseudotime, however, you'd need a significant amount of points to describe more complex patterns.
That said, while in principle we can define a linear function by only 2 points, using only 2 points will not be useful for clustering genes in terms of their expression pattern, and a higher number of points are useful here.

**Comment by tinggithub33** [comment]
Hello@koenvandenberge,
Thank you for your reply! that is very helpful.
since I am using real time-point instead of pseudotime, if I have 5 time points (2, 4,8,12,24 hr), should I use nkots =5, or 4 for fitGAM.
Thanks

**Comment by koenvandenberge** [comment]
We have functionality in `tradeSeq` that helps you choose the number of knots, see the `evaluateK` function and [this section of one of our vignettes](https://bioconductor.org/packages/release/bioc/vignettes/tradeSeq/inst/doc/tradeSeq.html#fit-negative-binomial-model). 
Since you only have 5 distinct time points, I would definitely go with less than 5 knots. I would think that 3 knots (which is the minimum in `tradeSeq`) should be sufficient. With 3 knots you'll fit 2 cubic functions, which you can think of as one cubic function for the data at timepoints 1-3 and the data for timepoints 3-5. 

Note that, if that may still be too complex, you could also fit a cubic function as such using a standard GLM without using `tradeSeq`.

**Comment by tinggithub33** [comment]
Hello @koenvandenberge,
very appreciate your comments!
1) evaluateK
I did evaluateK. Here is the graph. from the graph, do you think 4 knots is reasonable?
![image](https://user-images.githubusercontent.com/59709182/98713125-36972700-2355-11eb-89a9-526d7d7d9dee.png)
2) I will do fitGAM as above, then earlyDETest, diffEndRest, patternTest and clusterExpressionPatterns.
you mentioned "Since you only have 5 distinct time points, I would definitely go with less than 5 knots. I would think that 3 knots (which is the minimum in tradeSeq) should be sufficient. With 3 knots you'll fit 2 cubic functions, which you can think of as one cubic function for the data at timepoints 1-3 and the data for timepoints 3-5." 
I think this is what fitGAM does if use 3 knots. I am trying to make sure if I understand correctly? what if I use 4 knots? will I still fit 2 cubic functions, one is for the data at timepoints 1-4 and another one is for the data 2-5?
Thank you very much!

**Comment by koenvandenberge** [comment]
Hi @tinggithub33 

Apologies for my late reply.
From the `evaluateK` plot, it does seem like `k=4` knots is reasonable. One could say that `k=5` knots is also reasonable, but since we know that you only have 5 timepoints it seems like an overkill.

Yes, I was referring to `fitGAM` when discussing the knots above. If you have 4 knots, you will have three cubic functions. The start and the end of each of those cubic functions will depend on your data; by default we use the quantiles of the time variable to position knots (e.g., if `k=3`, the three knots will be at the minimum, median and maximum).
If you would like to understand better how the smoothing works, I recommend you take a look at the slides from the courses of Simon Wood, which you can find online here: https://www.maths.ed.ac.uk/~swood34/mgcv/
