### ISSUE TITLE
TradeSeq on scATAC Data 

### ISSUE THREAD

**Issue by Seandelao** [statOmics/tradeSeq#85]
Hello, 

I was wondering if it is possible to utilize TradeSeq on scATAC Seq data? I've been using the package ArchR to analyze my data, which supports Monocle3 and SlingShot for trajectory inference. What would be the appropriate "assay" to use; peaks, Gene activity matrix, etc? 

Thanks!

**Comment by koenvandenberge** [comment]
Hi @Seandelao 

It is an interesting question, and I would think that, in theory, it should work. After preprocessing, your scATAC-seq data should similarly consist of a count matrix; peaks in rows and cells in columns, which could also be provided to `tradeSeq`. 

Based on my current understanding of `ArchR`, your gene activity matrix are not counts, and correspond to estimated gene expression activity based on the chromatin accessibility. I have too little experience with the activity estimates from `ArchR` to suggest a proper distribution here; e.g. Gaussian could be appropriate but I have not empirically evaluated that, sot it may as well not. I would suggest to reach out to the developers of `ArchR` for this.

The peak count matrix could in principle be used directly into `fitGAM`. Since you typically have much more peaks than genes, I would suggest to filter peaks before you do this, using a filtering criterion you think is relevant (e.g. peaks close to genes / gene promotors and with reasonable accessibility).

It would be great if you could let us know how this works out for you.
