### ISSUE TITLE
how to add batch information in fitGAM

### ISSUE THREAD

**Issue by wangmhan** [statOmics/tradeSeq#97]
Hi,

Here is my situation. I would like to identify temporally expressed genes, while my data is generated from 3 different batches. I do see a batch effect in my UMAP, so I use Seurat IntegrationData to correct.
But to identify temporally expressed genes, seems better to using RNA counts instead of integrated data. As the instruction mentioned, fixed effect can be created by model.matrix. I just wonder if my command is correct or not, here it is:
my.meta =data.frame(batch=batch, pseudotime=slingPseudotime(crv, na = FALSE))
sce <- fitGAM(counts = counts, U=model.matrix(~ pseudotime + batch, my.meta),
                         sds = crv, nknots = 6, verbose = FALSE)
Is it right?

Another small question, is it only possible to deal with one lineage each time? As one lineage usually do not include all cells, do I need to subset the cells first?

Thank you & looking forward to the reply!

**Comment by koenvandenberge** [comment]
Hi @wangmhan 

Thanks for your interest in using `tradeSeq`. We generally recommend to integrate the data and estimate the trajectory using the integrated data, as you also seem to do.
For the fitting, you're right that it's recommended to use the counts instead of the integrated data. Since the pseudotime is automatically modeled using `fitGAM` there's no need to add it to the model matrix, as you do. Instead, I would recommend 

`sce <- fitGAM(counts = counts, U=model.matrix(~  batch, my.meta), sds = crv, nknots = 6, verbose = FALSE)`.

`tradeSeq` automatically handles multiple lineages, if they are present in your Slingshot object, `crv`.

**Comment by wangmhan** [comment]
Hi Koen,

Thank you for the nice instruction, it helps! And yes, I used integrated
data to estimate the trajectory.

For the multiple lineages, actually only one of them is interesting to us.
As we want to look into the dynamics of how it differentiated, so maybe I
can just subset and analyse only cells on that lineage in my case.

**Comment by koenvandenberge** [comment]
Hi @wangmhan 

Note that all DE tests have arguments that allow you to do the comparisons per lineage separately (for within-lineage tests e.g. `associationTest`) or for all pairwise comparisons (for between-lineage tests e.g. `patternTest`).
