### ISSUE TITLE
Degrees of Freedom in conditionTest?

### ISSUE THREAD

**Issue by kmshort** [statOmics/tradeSeq#98]
Hi all,

What are the degrees of freedom in conditionTest derived from?
If df=2, does that mean that the WaldStat was derived from values from 2 knots (after fitGAM processing)?

On a conditionTest performed on the results of fitGam with 6 knots, I see a max $df of 6, and a minimum df of 2.
In interpreting the results, are there any considerations a gene having a higher df? is the calculation of a waldstat for a df=6 gene more robust than a different gene which has df=2?

If no, can we interpret anything else based on the df of a waldstat calculated for a gene?

thanks.

**Comment by koenvandenberge** [comment]
Hi @kmshort 

I assume you have one lineage fitted using 6 knots, and 2 conditions.
The `conditionTest` compares expression at the knot points so naturally the maximum degrees of freedom will be 6. 
The actual number of degrees of freedom for each gene are derived from the variance-covariance matrix of the contrasts you are looking at. Let Sigma be the estimated variance-covariance matrix of your six contrasts, then the degrees of freedom for the `conditionTest` for each gene are defined by the rank of Sigma. The rank is defined by a threshold on the eigenvalues of Sigma, and the threshold can be tuned using the `eigenThresh` argument in `conditionTest`, `patternTest` and `earlyDETest`. The code for determining the rank is [here](https://github.com/statOmics/tradeSeq/blob/master/R/utils.R#L363). 

When a gene has a lower df for the test it means that some of the contrasts do not provide additional information given the other contrasts. This often happens when the functions you are testing are not very complex or when there are few cells expressing the gene. Indeed a gene with df=2 will often have simple patterns or few cells being expressed, as compared to a gene with higher df.

Hope this helps.
